### ISSUE TITLE
Small mistake in 'Plans'

### ISSUE THREAD

**Issue by mblarsen** [egoist/feedbackok-js#3]
Hi @egoist congrats on the release. Style of the site looks great.

The free plan has 'branding' but pro plan has 'no branding' or is it the other way around :smile: 
![image](https://user-images.githubusercontent.com/247048/90245475-55c10e00-de65-11ea-9d6f-e3e4aa711e7b.png)

**Comment by egoist** [comment]
I think that's correct, no branding means no `Powered by Feedback OK` in the widget.

**Comment by mblarsen** [comment]
Ah I understood branding as the ability to customize the widget to match your own brand. 

Can work both ways.
